#!/bin/bash

## Files and cmd
EWW="eww -c $HOME/.config/eww/"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
${EWW} open bar
