#!/bin/zsh

alias dots="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias ..='z ..'
alias cd='z'
alias zrc="nvim $HOME/.config/zsh/.zshrc"
alias ga='git add'
alias gc='git commit -m'
alias push='git push'
alias weather='curl -s "https://wttr.in/?1n"'
alias vps='ssh -p 54783 demon@3.108.32.164'
alias pacgraph='pacgraph --show-req-by -b "#232738" -l "#9778d3" -t "#cca9c6" -d "#b8d0eb"'
alias grep='grep --color=auto'
alias stow='stow --ignore=.git'
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"
alias monerod='monerod --data-dir "$XDG_DATA_HOME"/bitmonero'
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"
alias diff='diff --color=auto'
alias df='duf -hide special'
#alias aria2c="aria2c --file-allocation=none"
alias neofetch='neofetch --kitty ~/.config/neofetch/neofetch.jpeg --size 20%'

alias cat="bat --paging=never"
alias less="bat --paging=always"
alias x='exit'

if [ "$TERM" = "linux" ] ; then
        alias ls='/bin/ls --color=auto'
else
        alias ls='exa --icons'
        alias ll='exa -lgh --icons'
        alias la='exa -lagh --icons'
fi

# Confirmations
alias mv='mvg -ig'
alias rm='rip -i'
alias ln='ln -i'
alias cp='cpg -ig'

alias shred='shred -f -u -z -v -n 3'

# QoL
alias e="$EDITOR"
alias c='clear'
alias xcc='xclip -selection clipboard'
alias xco='xclip -selection clipboard -o'

# Package Management
alias install="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S"
alias uninstall="paru -R --noconfirm"
alias update="paru -Syu --noconfirm"
alias garbage="paru -Rcns $(paru -Qqdtt)"
