#!/bin/zsh

alias sch="sudo systemctl set-environment SCX_SCHEDULER_OVERRIDE=scx_lavd && sudo systemctl restart scx"

#alias dots="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias ..='cd ..'
alias zrc="nvim $HOME/.config/zsh/.zshrc"

# git stuffs
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gu='git pull'
alias gd='git diff'
alias gl="git log --all --graph --pretty=format:'%C(magenta))%h %C(white) %an  %ar%C(auto) %D%n%s%n"
alias gb='git branch'
alias gi='git init'
alias gcl='git clone'

alias weather='curl -s "https://wttr.in/?1n"'
alias pacgraph='pacgraph --show-req-by -b "#232738" -l "#9778d3" -t "#cca9c6" -d "#b8d0eb"'
alias grep='grep --color=auto'
alias stow='stow --ignore="screenshot.png" --ignore="README.org" --ignore=".git" --ignore=".assets" --ignore="deploy.sh"'
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"
alias diff='diff --color=auto'
alias df='duf -hide special'
alias neofetch="fastfetch --kitty ~/.config/fastfetch/logos/arch-logo.png --logo-width 45"
alias irssi="irssi --config=$XDG_CONFIG_HOME/irssi/config --home=$XDG_DATA_HOME/irssi"
alias cat="bat --paging=never"
alias less="bat --paging=always"
alias x='exit'
alias logout='pkill -u $USER'
alias dir='dir --color=auto'
alias pdfmaker="pandoc --pdf-engine=pdfroff \$1 -o \$2.pdf"
alias networkusage='vnstat -i wlo1'
alias b='brightnessctl set'
alias hostname="hostnamectl hostname"
alias wiki="nvim $XDG_DATA_HOME/vimwiki/index_$(date '+%a-%d-%m-%y-%H:%M').wiki"
alias dosbox="dosbox -conf $XDG_CONFIG_HOME/dosbox/dosbox.conf"
alias adb="HOME=$XDG_DATA_HOME/android adb"
alias time='hyperfine'
alias tor='webtorrent --mpv'
alias thumb='yt-dlp --write-thumbnail --skip-download'
alias SS='sudo systemctl'
alias j='sudo journalctl'
alias lsusb='cyme --headings --tree --hide-buses'
alias wget='wcurl'
alias open='xdg-open'
alias loc='~/.local/share/go/bin/scc'
alias rtmp='podman run -d -p 1935:1935 --name nginx docker.io/tiangolo/nginx-rtmp'
alias lf='yazi'
alias dfm='demonfm'

if [ "$TERM" = "linux" ] ; then
        alias ls='/bin/ls --color=auto'
else
        alias ls='eza --icons --group-directories-first'
        alias ll='eza -lgh --icons --group-directories-first'
        alias la='eza -lagh --icons --group-directories-first'
        alias tree='eza -aT --icons'
fi

# Confirmations
alias mv='mvg -ig'
alias rm='rip -i --graveyard $HOME/.local/share/Trash'
alias ln='ln -i'
alias cp='cpg -ig'

#alias shred='shred -f -u -z -v -n 3'

# QoL
alias e="$EDITOR"
alias edit='msedit'
alias c='clear'
alias xcc='xclip -selection clipboard'
alias xco='xclip -selection clipboard -o'
alias pbcopy='wl-copy'
alias pbpaste='wl-paste'

# Package Management
alias install="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S"
alias uninstall="paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro paru -Rcns"
alias update="paru -Syu --noconfirm"
alias garbage='paru -Rcns $(paru -Qqdtt)'
