#!/bin/zsh

# To start wayland session
if [ "$TTY" = "/dev/tty1" ]; then
    printf "\033[1;32mBooting into graphical session!\033[0m\n"
    #sx "$XDG_CONFIG_HOME/X11/xinitrc" -- -keeptty 2> /dev/null
    $HOME/.local/bin/startw -- -keeptty > $XDG_RUNTIME_DIR/startw.log
    #startplasma-wayland
fi


#export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

export PATH="$PATH:$HOME/.local/share/go/bin"

# Adds '~/.scripts' and all directories in $PATH
# export PATH="$PATH:$(du "$HOME/.scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
