#!/bin/bash

# Source pywal colors
source ~/.cache/wal/colors.sh

cat > colors.css << EOF
/* Custom color mappings for Waybar */
@define-color bg_primary ${color0}CC;
@define-color border_primary $color8;
@define-color text_primary $color7;
@define-color text_critical $color1;
@define-color text_blink $color15;
@define-color bg_transparent transparent;
@define-color color_transparent transparent;
EOF

