# HYPRLAND - alba4k
#
# Documentation: https://wiki.hyprland.org
#
# ##############################################
# ###                 COLORS                 ###
# ##############################################

# Accents (replacing with $iris from Rosé Pine)
###$C_PRIMARY = rgb(C5AAE5) #rgb(c4a7e7)
###$C_PRIMARY_DARK = rgb(403d52) # Using $highlightMed
###
#### Inactive borders (replacing with a semi-transparent version of $muted)
###$C_INACTIVE = rgba(6e6a8690)
###
#### Background objects (replacing with $surface)
###$C_BACKGROUND = rgb(1f1d2e)
###
#### Text (replacing with $text and $subtle)
###$C_FOREGROUND = rgb(e0def4)
###$C_PALE_FOREGROUND = rgb(908caa)
###

# Accents (replacing with $iris from Rosé Pine → purple in Tokyo Night)
$C_PRIMARY = rgb(bb9af7) #rgb(bb9af7)
$C_PRIMARY_DARK = rgb(292e42) # Using bg_highlight
# Inactive borders (replacing with a semi-transparent version of $muted)
$C_INACTIVE = rgba(565f8990)
# Background objects (replacing with $surface)
$C_BACKGROUND = rgb(1f2335)
# Text (replacing with $text and $subtle)
$C_FOREGROUND = rgb(c0caf5)
$C_PALE_FOREGROUND = rgb(a9b1d6)
