#!/bin/sh

#swhkd &
xrdb -merge ~/.Xresources &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
waybar &
dunst &
swaybg -i /home/demonkingswarn/hdd/pix/wall/87.jpg &
/home/demonkingswarn/.scripts/system/waylock.sh &
