#!/bin/sh

TERM="wezterm"
ALT_TERM="ghostty"
LAUNCHER="rofi -show drun"
FILE_MANAGER="thunar"
LOCK_PROGRAM="$HOME/.scripts/system/waylock.sh"
SS_PROGRAM="$HOME/.config/hypr/scripts/screenshot"
EMOJI_PROGRAM="$HOME/.scripts/emojis/emoji.sh"
WALL_PROGRAM="$HOME/.scripts/misc/wallmanager"

wlr-randr --output eDP-1 --mode 1920x1080@60.004002 &

riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment QT_QPA_PLATFORMTHEME"

# theme

riverctl spawn "gsettings set org.gnome.desktop.interface gtk-theme 'gtk-master'"
riverctl spawn "gsettings set org.gnome.desktop.wm.preferences theme 'gtk-master'"
riverctl spawn "gsettings set org.gnome.desktop.interface icon-theme 'Dracula'"
riverctl spawn "gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Amber'"
riverctl xcursor-theme "Bibata-Modern-Amber"

# keyboard layout

riverctl keyboard-layout -variant ,digits -options ctrl:nocaps us

# touchpad things

touchpad_settings() {
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad events enabled
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad tap enabled
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad drag enabled
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad drag-lock disabled
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad scroll-method edge
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad disable-while-typing enabled
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad tap-button-map left-right-middle
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad natural-scroll enabled
        riverctl input pointer-1267-12525-ELAN0710:01_04F3:30ED_Touchpad scroll-factor 1.5
}

touchpad_settings



# Set keyboard repeat rate
riverctl set-repeat 69 300

# server side decorations
riverctl rule-add ssd

# Set new windows to always split horizontally or vertically based on ratio
riverctl set-layout simple

# Focus new views automatically
riverctl set-view-focus new

# Automatically make certain new windows tile if possible
riverctl rule-add view float=false

riverctl rule-add app-id "pavucontrol" float
riverctl rule-add app-id "blueman-manager" float
riverctl rule-add app-id "nm-connection-editor" float
riverctl rule-add app-id "thunar" float
riverctl rule-add -title "galculator" float
riverctl rule-add app-id "hyprland-share-picker" -title "MainPicker" float

## Keybinds

# Applications
riverctl map normal Super Return spawn "$TERM"
riverctl map normal Alt Return spawn "$ALT_TERM"
riverctl map normal Super d spawn "$LAUNCHER"
riverctl map normal Super e spawn "$EMOJI_PROGRAM"
riverctl map normal Super w spawn "$WALL_PROGRAM"
riverctl map normal Super+Shift x spawn "$LOCK_PROGRAM"
riverctl map normal Super i spawn "$TERM -e htop"

# special function keys
riverctl map normal None XF86Explorer spawn "$FILE_MANAGER"
riverctl map normal None XF86Calculator spawn galculator
riverctl map normal None XF86Search spawn "rofi -no-lazy-greb -show file-browser-extended -icon-theme 'Dracula'"
riverctl map normal None XF86Tools spawn 'brave --app="https://music.youtube.com"'

# reload configuration
riverctl map normal Super+Shift r spawn "source ${XDG_CONFIG_HOME:-$HOME/.config}/river/init"

# media control
riverctl map normal None XF86AudioPlay spawn "playerctl play-pause"
riverctl map normal None XF86AudioNext spawn "playerctl next"
riverctl map normal None XF86AudioPrev spawn "playerctl previous"

riverctl map normal Super V toggle-float
riverctl map normal Super F toggle-fullscreen

# makes it easier for moving floating windows
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# screenshot
riverctl map normal None Print spawn "$SS_PROGRAM fullsave"
riverctl map normal Super Print spawn "$SS_PROGRAM selclip"

# Window movement (Vim style)
riverctl map normal Super H focus-view -skip-floating left
riverctl map normal Super J focus-view -skip-floating down
riverctl map normal Super K focus-view -skip-floating up
riverctl map normal Super L focus-view -skip-floating right

# Close window
riverctl map normal Super+Shift Q close

# Switch and move between tags
for i in $(seq 1 9); do
  riverctl map normal Super $i set-focused-tags $((1 << ($i - 1)))
  riverctl map normal Super+Shift $i set-view-tags $((1 << ($i - 1)))
done

# scratch pad
scratchTag=$((1 << 20))
riverctl map normal Super 0 toggle-focused-tags $scratchTag
riverctl map normal Super+Shift 0 set-view-tags $scratchTag
riverctl spawn-tagmask $((((1 << 32) - 1) ^ scratchTag))

stickyTag=$((1 << 10))
riverctl map normal Super S toggle-view-tags $stickyTag
riverctl spawn-tagmask $((((1 << 32) - 1) ^ stickyTag))

# Exit river
riverctl map normal Super+Shift M exit

# Volume Control
riverctl map normal None XF86AudioRaiseVolume spawn "pamixer -i 5"
riverctl map normal None XF86AudioLowerVolume spawn "pamixer -d 5"
riverctl map normal None XF86AudioMute spawn "pamixer -t"

# Gaps and borders
riverctl border-width 3
riverctl set-cursor-warp on-focus-change
riverctl background-color 0x161616
riverctl border-color-focused 0xbd93f9
riverctl border-color-unfocused 0x282828

# Start background services
riverctl spawn "$HOME/.config/autostart/startup.sh"

killall wideriver
riverctl default-layout wideriver
# --no-smart-gaps                            \
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        dwindle     \
    --count-master                 1           \
    --smart-gaps  \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --inner-gaps                   6           \
    --outer-gaps                   6           \
    --border-width                 2           \
    --border-width-monocle         0           \
    --border-width-smart-gaps      0           \
    --border-color-focused "0xaa86e1" \
    --border-color-unfocused "0x282828" \
    --border-color-focused-monocle "0xbd93f9"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

riverctl set-cursor-focus-follows-mouse enabled
riverctl focus-follows-cursor normal
