#!/bin/sh

wlr-randr --output eDP-1 --mode 1920x1080@60.00 &

# Set keyboard repeat rate
riverctl set-repeat 69 300

# server side decorations
riverctl rule-add ssd

# Set new windows to always split horizontally or vertically based on ratio
riverctl set-layout simple

# Focus new views automatically
riverctl set-view-focus new

# Automatically make certain new windows tile if possible
riverctl rule-add view float=false

riverctl rule-add app-id "pavucontrol" float=true
riverctl rule-add app-id "blueman-manager" float=true
riverctl rule-add app-id "nm-connection-editor" float=true
riverctl rule-add app-id "thunar" float=false

# Applications
riverctl map normal Super Return spawn wezterm
riverctl map normal Alt Return spawn ghostty
riverctl map normal Super d spawn "rofi -show drun"
riverctl map normal Super e spawn "~/.scripts/emojis/emoji.sh"
riverctl map normal Super w spawn "$HOME/.scripts/misc/wallmanager"

# Clipboard history picker using cliphist + fuzzel
#riverctl map normal Super v spawn "sh -c 'cliphist list | fuzzel --dmenu | cliphist decode | wl-copy'"

# Full screen screenshot (Print key)
riverctl map normal None Print spawn "$HOME/.config/hypr/scripts/screenshot fullsave"
riverctl map normal Super Print spawn "$HOME/.config/hypr/scripts/screenshot selclip"

# Window movement (Vim style)
riverctl map normal Super H focus-view -skip-floating left
riverctl map normal Super J focus-view -skip-floating down
riverctl map normal Super K focus-view -skip-floating up
riverctl map normal Super L focus-view -skip-floating right

# Close window
riverctl map normal Super+Shift Q close

# Switch and move between tags
for i in $(seq 1 9); do
  riverctl map normal Super $i set-focused-tags $((1 << ($i - 1)))
  riverctl map normal Super+Shift $i set-view-tags $((1 << ($i - 1)))
done

# Exit river
riverctl map normal Super+Shift M exit

# Volume Control
riverctl map normal None XF86AudioRaiseVolume spawn "pamixer -i 5"
riverctl map normal None XF86AudioLowerVolume spawn "pamixer -d 5"
riverctl map normal None XF86AudioMute spawn "pamixer -t"

# Set wallpaper
# Moved to swww
#swaybg -i ~/.cache/wall.jpg -m fill &

# Dark mode and styling environment variables (INLINE)
#export GTK_THEME=gtk-master &
#export XCURSOR_THEME=Bibata-Modern-Amber &
#export XCURSOR_SIZE=24 &
#export QT_QPA_PLATFORMTHEME=qt5ct &
#export QT_STYLE_OVERRIDE=kvantum &

# Gaps and borders
riverctl border-width 3
riverctl set-cursor-warp on-focus-change
riverctl background-color 0x161616
riverctl border-color-focused 0xbd93f9
riverctl border-color-unfocused 0x282828

# Start background services
$HOME/.config/autostart/startup.sh

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

riverctl set-cursor-focus-follows-mouse enabled
