#!/usr/bin/env sh

$HOME/.scripts/system/startup.sh &


if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
else
	. "$HOME/.xprofile"
fi


exec bspwm
#exec leftwm
#exec openbox

#### GNOME Session ####
#export XDG_SESSION_TYPE=x11
#export GDK_BACKEND=x11
#exec gnome-session
