#!/bin/sh

x="Screenshot copied to clipboard"
name="shot_$(date '+%y%m%d_%H-%M-%S')"

[ "$*" = "fullsave" ] && flameshot full -c --path $HOME/pix/ss/$name && notify-send -i $HOME/pix/ss/$name.png "Screenshot saved" "$HOME/pix/ss/$name.png"

[ "$*" = "selclip" ] && flameshot gui
