#!/bin/sh

TOGGLE="$HOME/.cache/toggle_shader"

if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    hyprctl keyword decoration:screen_shader '~/.config/hypr/shaders/grayscale.frag'
else
    rm $TOGGLE
    hyprctl keyword decoration:screen_shader ''   
fi
