source = ~/.config/hypr/include/colors.conf

## General configs
general {
    ignore_empty_input = true
    hide_cursor = true
}

auth {
    fingerprint:enabled = false
}

animations {
    enabled = false
}

# Blurred background
background {
    monitor =
    color = $color
    path = /home/swarn/.cache/lock.png
    blur_passes = 3
    blur_size = 8
}

## Password field
input-field {
    monitor =
    size = 880, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4
    dots_size = 0.24
    dots_spacing = 0.24

    font_family = LythMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

## Top bar
shape {
    size = 100%, 52
    position = 0, 0
    halign = center
    valign = top
    color = rgba(34,34,34,1)
    border_size = 0
    rounding = 0
}

## Clock
label {
    text = $TIME
    font_size = 18
    halign = center
    valign = top
    position = 5, -9
    font_family = LythMono Nerd Font Propo
    color = rgba(194,194,176,1)
}

## Right portion of top bar
label {
    text = cmd[update:2000] hyprlock-bar-right
    font_size = 18
    text_align = right
    halign = right
    valign = top
    position = -32, -9
    font_family = LythMono Nerd Font Propo
    color = rgba(194,194,176,1)
}

## System info line
label {
    text = cmd[update:3600000] hyprlock-system-info
    font_size = 14
    halign = center
    valign = bottom
    position = 0, 180
    font_family = LythMono Nerd Font
    color = rgba(194,194,176,1)
}

## KVM label
label {
    text = cmd[update:2000] bash -c 'grep -q "Name=\"CX 2.4G Wireless Receiver Keyboard\"" /proc/bus/input/devices && echo "KVM"'
    font_size = 14
    halign = center
    valign = center
    position = 380, 0
    font_family = LythMono Nerd Font
    color = rgba(194,194,176,0.72)
}

## Bindings
#label {
#    text = <span weight="bold" alpha="72%">[Super+Esc]</span> <span alpha="56%">Display off</span>   <span weight="bold" alpha="72%">[Super+S]</span> <span alpha="56%">Suspend</span>   <span weight="bold" alpha="72%">[Super+R]</span> <span alpha="56%">Reboot</span>   <span weight="bold" alpha="72%">[Super+P]</span> <span alpha="56%">Power off</span>
#    font_size = 14
#    halign = center
#    valign = bottom
#    position = 0, 256
#    font_family = LythMono Nerd Font
#    color = rgba(194,194,176,1)
#}
