#!/bin/sh

x="Screenshot copied to clipboard"
name=$(date '+%y%m%d_%H-%M-%S')
[ "$*" = "fullclip" ] && grim - | xclip -sel c -t image/png
[ "$*" = "fullsave" ] && grim $HOME/pix/ss/$name.png && cat $HOME/pix/ss/$name.png | wl-copy && x="Screenshot saved"
[ "$*" = "selclip" ] && grim -g "$(slurp)" - | swappy -f -

notify-send "$x"
