#!/bin/sh

x="Screenshot copied to clipboard"
name="shot_$(date '+%y%m%d_%H-%M-%S')"

hyprpicker -r -z &
sleep 0.1

[ "$*" = "fullsave" ] && grim $HOME/pix/ss/$name.png && cat $HOME/pix/ss/$name.png | wl-copy && x="Screenshot saved"

[ "$*" = "selclip" ] && grim -g "$(slurp)" - | swappy -f -

notify-send "$x"
killall hyprpicker
