#!/bin/sh

while read file
do
	case "$1" in 
        "c") wl-copy < "$file" ;;
        "w") swww clear && cp "$file" "$HOME/.cache/wall.jpg" && swww img $HOME/.cache/wall.jpg && notify-send -i "$HOME/.cache/wall.jpg" "Wallpaper changed." ;;
        "r") convert "$file" -rotate 90 /tmp/out.jpg ;;
        "m") curl -F"file=@$file" 0x0.st | wl-copy ;;
        "t") "$BROWSER" "$(zbarimg -q "$file" | awk -F'QR-Code:' '{print $2}')" ;;
        "i") notify-send -i $file "File information" "$(mediainfo $file)" ;;
        "y") readlink -f "$file" | wl-copy && notify-send "$(readlink -f "$file") copied to clipboard" ;;
	esac
done
