#!/bin/sh

while read file
do
	case "$1" in 
		"c") cat "$file" | wl-copy ;;
		"r") convert "$file" -rotate 90 /tmp/out.jpg ;;
		"m") curl -F"file=@$file" 0x0.st | wl-copy ;;
        "t") zbarimg -q "$file" | awk -F'QR-Code:' '{print $2}' | wl-copy ;;
	esac
done
