general.live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.cursor]
background = "0x7aa2f7"
foreground = "0x1a1b26"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false

[font]
size = 16

[font.bold]
family = "LythMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "LythMono Nerd Font"

[font.normal]
family = "LythMono Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[mouse]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 15000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
program = "/usr/sbin/zsh"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 10
y = 10
